"""Added to user column for tracking if user 'registered' themselves so that we can get their swimrankings pbs

Revision ID: 63f865952095
Revises: 
Create Date: 2025-05-02 13:21:35.736052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f865952095'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_swimrankings', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('added_swimrankings')

    # ### end Alembic commands ###
