"""removed personal bests for now

Revision ID: d891d3ad635c
Revises: 63f865952095
Create Date: 2025-05-03 11:42:08.581131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd891d3ad635c'
down_revision = '63f865952095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal_bests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_bests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event', sa.VARCHAR(length=120), nullable=False),
    sa.Column('course', sa.VARCHAR(length=120), nullable=False),
    sa.Column('time', sa.VARCHAR(length=120), nullable=False),
    sa.Column('updated', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
